//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public string ISN { get; set; }
        public string Titulo { get; set; }
        public int Total_Paginas { get; set; }
        public System.DateTime Fecha_Publicacion { get; set; }
        public int IdEditorial { get; set; }
        public int IdAutor { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Editorial Editorial { get; set; }
    }
}
